version: '3.3'
services:
#  web:
#    build:
#      context: ./bacabaca
#    restart: always
#    ports:
#      - "10048:8080"
#    volumes:
#      - ./file-storage:/file-storage
#      - ./log:/log
#    env_file:
#      - bacabaca/.env
#    depends_on:
#      - db
#    networks:
#      - frontend-network
#      - backend-network
#  web2:
#    build:
#      context: ./pacil
#    restart: always
#    ports:
#      - "10049:8081"
#    volumes:
#      - ./file-storage:/file-storage
#      - ./log:/log
#    networks:
#      - frontend-network
#      - backend-network

  db:
    image: postgres:14-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db:
    driver: local

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
